[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://apparel-ec.netlify.app/.netlify/functions"
  NEXT_PUBLIC_BASE_URL = "https://apparel-ec.netlify.app"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-audit --no-fund"
  NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.stripe.com https://apparel-ec.netlify.app; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production]
  environment = { NODE_ENV = "production" }

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"